### ISSUE TITLE
Craft: Events Should be Featurable

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#102]
Need a way to mark an event as featured in the admin.

**Comment by acolangelo** [comment]
This is possible via [the Events entry](http://107.170.57.118/admin/entries/events/5-events):
![screen shot 2017-05-11 at 7 35 05 am](https://cloud.githubusercontent.com/assets/462291/25947201/62e4b5b8-361c-11e7-9b83-de8dcccb97cd.png)

**Comment by sarawb** [comment]
Ah, I see. I was anticipating marking an event itself as featured, not adding items to the Events page.

This is going to cause some problems for management -- I see this being left empty quite a lot without some fallback logic being in place.

Is there a way to mark an individual event as featured when submitting it rather than having to add featured events to the Events page? That would help with the sort of workflow they have. If so, behavior would be: always show next 3 upcoming featured events, and if 3 events aren't marked as featured, then default to feature any next 3 events. 
 
If we have to add featured events from the Events page, we still need some logic to populate this space when no one has added anything or the events they've added have passed.

**Comment by acolangelo** [comment]
Ah, I see. I’ll rework and orient this around the events themselves.
