### ISSUE TITLE
Craft form - Date of contact field should be date selection

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#146]
Is currently open text; this is read only for me so I can't fix it.

**Comment by alexroper** [comment]
There isn't a field type that let's you select a date.

We could either add a placeholder in the field that suggests the format like "e.g. 01/01/2017" or "mm/dd/yyyy" or "Jan 1, 2017."

The other option would be to try and build a javascript custom solution for this like jQuery UI. Is that the kind of thing you're thinking of?

https://jqueryui.com/datepicker/

Freeform doesn't let you change the field type after you create it. It's a slightly annoying quirk of the system. Probably because it might mess with already submitted data. The only way around it is to delete the old field and create a new one.

**Comment by sarawb** [comment]
Yeah, I am surprised there's no datepicker in freeform! 

The issue on this particular form is that people routinely get in touch without a specific date in mind, and the organizers can't manage the back-and-forth of connecting speakers to events when the events are not already earmarked for a firm date. So we want to avoid allowing people to enter non-date data like "early July" in that field, which is what they tend to do now.

So....if we can possibly add a datepicker, that would be awesome. How much work is that?

**Comment by sarawb** [comment]
Per Slack convo, @wnstn to work on this tonight
