### ISSUE TITLE
Need statewide event style for featured slot

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#149]
When an event is a conference call or statewide event like the rally and is featured, it should have a STATEWIDE label where the others have EASTERN, and an icon in FDPA orange showing the whole state filled in. 
Date should also display same place as it does in other events; just won't have a city next to it. 

![image](https://cloud.githubusercontent.com/assets/3171996/26174587/e660282c-3b1d-11e7-8145-a90124d1f92e.png)

**Comment by alexroper** [comment]
I changed the logic per issue #136 so that there are now 3 event slots, but only 1 per region.

Now the scenario in the above screenshot won't happen (2 Eastern events and a statewide event). The only reason that happened is because previously I was just pulling the next events to fill those slots regardless of regions.

If we want to add Statewide events into the mix again, we'll have to change the logic further. If we do that, I'm not sure how we would prioritize regions vs statewide events.

For example, in each slot, it would go thru this list looking for a match in order of importance:

1. Next featured regional event
2. Next featured statewide event
3. Next regional event
4. Next statewide event

**Comment by sarawb** [comment]
I think we can leave this as is; we can look at logic in the future if it becomes an issue.
