### ISSUE TITLE
Mailgun -transactional email setup

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#185]
Per convo with @alexroper: 

- We are going to use Mailgun for transactional email
- Alex has set up the account and will get that rolling 
- Sara to follow up with FDPA to get CC on file (but we should stay at free level) -- need CC to send email beyond sandbox list 
- Transactional email will not be used for the Join and Volunteer forms bc those are Action Network

**Comment by alexroper** [comment]
I think the next step in this process would be to change the client's DNS servers to Digital Ocean instead of Wix. Once that happens, we can add the new DNS records Mailgun needs to work.

I can't do this because I don't have access to their Digital Ocean or Wix account.

It looks like they are using Google for email hosting so that should make things a little easier to transfer.

https://who.is/dns/fairdistrictspa.com

**Comment by alexroper** [comment]
FYI, here are the DNS records we need to add.

Note: The MX records are for a subdomain, mg.fairdistrictspa.com, not to be confused with the Gmail MX records that are on the main domain fairdistrictspa.com.

[FDPA mailgun settings.pdf](https://github.com/FDPA/fdpa/files/1048854/FDPA.mailgun.settings.pdf)

**Comment by sarawb** [comment]
Hey @alexroper -- got it, except for one thing I am not totally sure about: MX records. 

Here is the MX record it already had in place on the mg. subdomain: 

![image](https://cloud.githubusercontent.com/assets/3171996/26754603/ae8cdd60-484b-11e7-9469-4ae219eee2a2.png)

Should I change this, or add Mailgun's two MX records to this?

**Comment by sarawb** [comment]
(Nothing's propagated to Mailgun yet but I am keeping an eye to make sure the DNS shows as verified here eventually)

**Comment by sarawb** [comment]
Ok, Mailgun has us listed as verified, but I can't get non-sandbox email addresses to work. @alexroper are you able to help? Not sure what to do (my googling has not been fruitful).

**Comment by alexroper** [comment]
It looks like everything is working on Mailgun except the MX records. 

You should be able to add 2 new DNS records. The hostname should be a subdomain `@mg.fairdistrictspa.com`, not the main domain `@`.

type: MX
hostname: @mg.fairdistrictspa.com
priority: 10
value/mail server: mxa.mailgun.org

type: MX
hostname: @mg.fairdistrictspa.com
priority: 10
value/mail server: mxb.mailgun.org

![mailgun-mx-records](https://cloud.githubusercontent.com/assets/377542/26818815/0ab56c90-4a51-11e7-90fe-97620f450784.png)

**Comment by sarawb** [comment]
Hey Alex - sorry, missed this. The screenshot above is actually not how it's set up -- that was from Hover and before I realized I needed to do all this in Digital Ocean. But in DO, we have the MX records set for google apps, and the way I understand it, if you're doing that you don't add these. Everything seems to be working fine. Am I misunderstanding something?

**Comment by alexroper** [comment]
The Mailgun MX records are so that we can receive emails back to Mailgun. It's for things like if an email is undeliverable and it bounces back, that error email will go back to Mailgun. But it's only for the transactional emails Mailgun sends. Not any emails that go thru "@fairdistrictspa.com" email (e.g. Gmail).

Here's a FAQ about these settings:
https://help.mailgun.com/hc/en-us/articles/203357040-Can-I-use-the-same-domain-name-for-Mailgun-and-for-Google-Apps-or-another-email-server-

I added these into Digital Ocean's networking setup and it looks like they are working.
