### ISSUE TITLE
Which Front End Framework Should We Use?

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#4]
Here's what I'll say at the outset: I hate front end frameworks (CSS-wise) but I think they make the most sense for this project because they are well documented and will be easy to use for future needs that we may not be able anticipate now.

Here's a not-finalized screenshot of a local groups page to give you a sense of where design direction is headed.

![image](https://cloud.githubusercontent.com/assets/779882/25159638/3578387e-247f-11e7-9c97-854ed42e88f2.png)

This can easily be accomplished with most popular CSS frameworks. 

If you have an preference or experience that you feel would help in this project, feel free to comment here. If you feel like it, rank the strength of your opinion from 1 to 10, and if it's on the higher end feel free to add a couple points on why you think that. We'll try to land on something tomorrow and add it to the repo so we can start building views out.

**Comment by wnstn** [comment]
Popular frameworks that we might choose from (by no means exhaustive):

[Bootstrap](http://getbootstrap.com/)
[Semantic UI](https://semantic-ui.com/)
[Pure CSS](https://purecss.io/)
[Foundation](http://foundation.zurb.com/)

**Comment by onebrightlight** [comment]
I  vote we go with Pure as it’s got it’s basis in SMACSS, personally.

**Comment by alexroper** [comment]
I'm a SMACSS fan also, but I have the most experience with the Bootstrap framework. But I never build with the whole thing. Just pick and choose which pieces to use.

I've used Foundation a little bit, but it kind of changes too often for my tastes.

Pure looks interesting, but I haven't used it before. It's interesting that all the classes are prefixed with "pure-" so that you can use it on top of other frameworks like Bootstrap. Also, it looks like it doesn't use a CSS preprocessor like Sass to customize anything. It's all built with task runners like Grunt and Rework.

I haven't heard of Semantic UI, but something about class="ui three buttons" is just gross to me. 🤢

**Comment by esopp** [comment]
The only CSS framework I have significant experience with is Bootstrap-- which means it would be good for me to learn a new one.

**Comment by onebrightlight** [comment]
I'm also totally for Bootstrap. I've used all in the list. Personally I'm a Bourbon fan, but that doesn't have any classes as it’s entirely comprised of mixins.

**Comment by sarahbreiding** [comment]
I also have the most experience with Bootstrap - though I wouldn't say it's my favorite. I'd be happy to try out something else.

**Comment by wnstn** [comment]
Sounds like we have a strong vote in favor of Pure, a curiosity about it, and 3 people with experience  on Bootstrap voting for not it! I love it.

Let's go with Pure Css, I'll spin it up tonight.
