### ISSUE TITLE
Hook up district map on local group page

### ISSUE THREAD

**Issue by acolangelo** [FDPA/fdpa#51]
County data should be pulled out of Craft and handed off to map embed.

<img width="589" alt="screen shot 2017-05-03 at 7 53 09 pm" src="https://cloud.githubusercontent.com/assets/462291/25687060/1922b866-3041-11e7-8b4f-b21b09f8f4bf.png">

**Comment by sarawb** [comment]
Hello! Are there any blockers for this? @acolangelo is this something you were thinking you could help with? What's needed? (This is a blocker for review because those pages look broke without maps, and we need to make sure we have real, correct ones in there or local groups will find it confusing.)

**Comment by sarawb** [comment]
This is done, but issue #204 is open to tweak display of maps. Closing this issue.
