### ISSUE TITLE
Craft Twig: Turn static homepage into twig template

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#85]
Fields just need to be for the content blocks, everything else can be hard coded to the html.

Static homepage [is here](http://107.170.57.118/assets/theme/index.html)

**Comment by alexroper** [comment]
Hey @wnstn, can I ask what content you want editable here? And which part can be hard coded?

I could just make a bunch of Homepage specific fields like "Checkmark Callout 1" and "Checkmark Callout 2", etc. Or did you have something else in mind?

I get the feeling you don't need it to be super flexible (rearrange the entire page thru the CMS).

**Comment by sarawb** [comment]
@alexroper Yeah, just specific fields. We basically want to be able to adjust copy within blocks, but not redesign the page/rearrange the blocks on the fly. Here are the blocks I think will work. The first set of body content with the X bullets IMO should ideally be administrable as a chunk rather than per bullet (as in, it might in the future not have bullets or have more/less of them). Where we have sets of 3 items, I think we can force those to remain sets of 3. 

Illustrations do not need to be CMS-editable unless you want them to be. 

![image](https://cloud.githubusercontent.com/assets/3171996/25953216/b1e5c274-3630-11e7-8656-106edc68d7f6.png)
